
def calculate_total_cost(items, tax=True, shipping=True):
    base_price = calculate_base_price(items)
    taxes = calculate_taxes(items) if tax else 0
    shipping_fees = calculate_shipping_fees(items) if shipping else 0
    return base_price + taxes + shipping_fees

def calculate_base_price(items):
    return round(sum(item["Price"] * item["Quantity"] for item in items), 2)

def calculate_taxes(items):
    return round(sum(item["Price"] * item["Quantity"] * TAX_RATES[item["Location"]] for item in items), 2)

def calculate_shipping_fees(items):
    return round(sum(item["Weight"] * item["Quantity"] * SHIPPING_RATES[item["Location"]] for item in items), 2)


#Tax rates by country

TAX_RATES = {
    'Ivory Coast': 0.18,
    'Finland': 0.24,
    'Japan': 0.1,
    'Austria': 0.2,
    'Denmark': 0.25,
    'Sweden': 0.25,
    'Aruba': 0.03,
    'Belgium': 0.21,
    'Israel': 0.17,
    'Slovenia': 0.22,
    'Netherlands': 0.21,
    'Portugal': 0.23,
    'Ireland': 0.23,
    'Spain': 0.21,
    'Iceland': 0.24,
    'China': 0.13,
    'Germany': 0.19,
    'United Kingdom': 0.2,
    'France': 0.2,
    'South Africa': 0.15,
    'South Korea': 0.1,
    'Australia': 0.1,
    'Luxembourg': 0.17,
    'Greece': 0.24,
    'Italy': 0.22,
    'India': 0.18,
    'Papua New Guinea': 0.1,
    'Turkey': 0.18,
    'Uganda': 0.18,
    'Taiwan': 0.05,
    'Chile': 0.19,
    'Senegal': 0.18,
    'Zimbabwe': 0.14,
    'Guinea': 0.14,
    'Switzerland': 0.07,
    'Republic Of The Congo': 0.18,
    'Mauritania': 0.16,
    'Colombia': 0.19,
    'New Zealand': 0.15,
    'Morocco': 0.2,
    'Norway': 0.25,
    'Suriname': 0.1,
    'United States': 0,
    'Zambia': 0.16,
    'Namibia': 0.15,
    'Uruguay': 0.22,
    'Pakistan': 0.17,
    'Mexico': 0.16,
    'Ethiopia': 0.15,
    'Philippines': 0.12,
    'Vietnam': 0.1,
    'Thailand': 0.07,
    'Argentina': 0.21,
    'Algeria': 0.19,
    'Cameroon': 0.19,
    'Ecuador': 0.12,
    'Tunisia': 0.19,
    'Gabon': 0.18,
    'Equatorial Guinea': 0.15,
    'Cyprus': 0.19,
    'Malta': 0.18,
    'Venezuela': 0.16,
    'Canada': 0.05,
    'Puerto Rico': 0,
    'Poland': 0.23,
    'Mozambique': 0.17,
    'Latvia': 0.21,
    'Indonesia': 0.1,
    'Tanzania': 0.18,
    'Kenya': 0.16,
    'Peru': 0.18,
    'Malaysia': 0.1,
    'Ghana': 0.13,
    'Malawi': 0.16,
}


#Shipping rates by country per kg

SHIPPING_RATES = {
    'Ivory Coast': 5.4,
    'Finland': 3.1,
    'Japan': 5.5,
    'Austria': 3.8,
    'Denmark': 2.6,
    'Sweden': 2.8,
    'Aruba': 7.6,
    'Belgium': 3.5,
    'Israel': 5.0,
    'Slovenia': 4.5,
    'Netherlands': 3.9,
    'Portugal': 4.4,
    'Ireland': 3.5,
    'Spain': 4.0,
    'Iceland': 3.7,
    'China': 4.1,
    'Germany': 5.0,
    'United Kingdom': 4.3,
    'France': 4.5,
    'South Africa': 6.2,
    'South Korea': 5.6,
    'Australia': 5.1,
    'Luxembourg': 5.1,
    'Greece': 4.1,
    'Italy': 5.2,
    'India': 5.8,
    'Papua New Guinea': 6.8,
    'Turkey': 4.2,
    'Uganda': 8.1,
    'Taiwan': 9.8,
    'Chile': 7.6,
    'Senegal': 5.9,
    'Zimbabwe': 6.7,
    'Guinea': 6.2,
    'Switzerland': 3.9,
    'Republic Of The Congo': 6.9,
    'Mauritania': 6.1,
    'Colombia': 7.1,
    'New Zealand': 7.8,
    'Morocco': 4.8,
    'Norway': 2.3,
    'Suriname': 7.9,
    'United States': 2.7,
    'Zambia': 6.9,
    'Namibia': 6.1,
    'Uruguay': 6.7,
    'Pakistan': 5.6,
    'Mexico': 3.4,
    'Ethiopia': 6.6,
    'Philippines': 7.3,
    'Vietnam': 5.5,
    'Thailand': 5.3,
    'Argentina': 6.0,
    'Algeria': 5.0,
    'Cameroon': 6.0,
    'Ecuador': 7.9,
    'Tunisia': 5.6,
    'Gabon': 8.6,
    'Equatorial Guinea': 9.9,
    'Cyprus': 6.5,
    'Malta': 4.9,
    'Venezuela': 7.1,
    'Canada': 3.7,
    'Puerto Rico': 7.9,
    'Poland': 4.1,
    'Mozambique': 5.8,
    'Latvia': 4.9,
    'Indonesia': 8.0,
    'Tanzania': 9.2,
    'Kenya': 7.6,
    'Peru': 6.7,
    'Malaysia': 7.6,
    'Ghana': 7.4,
    'Malawi': 7.2
}